---
- include_tasks: install.yml
  when: install|bool

- include_tasks: configure.yml
  when: configure|bool

- include_tasks: nerdtree.yml
  when: nerdtree|bool

- include_tasks: themes.yml
  when: install_themes|bool

- include_tasks: icons.yml
  when: icons|bool

- include_tasks: powerline.yml
  when: powerline|bool

- include_tasks: syntax.yml

- include_tasks: support_golang.yml
  when: golang|bool
